### ISSUE TITLE
Show warning when dir(s) exist in an op collection that aren't valid ops

### ISSUE THREAD

**Issue by poppuyo** [opspec-io/opctl#114]
Only really ran into this when I ran `opctl ls` inside a collection of ops that were on the "stable" version while I was running the "beta" channel. I was briefly confused that I saw a subset of the ops I was expecting to see, and then I realized that it must be due to running in beta.

Suggested initial/naive implementation:
- Look at the sudirectories of .opspec
- Decide which of these translate to valid ops
- Show a warning (think compiler warnings) showing which directories didn't yield valid ops

**Comment by chrisdostert** [comment]
the concept of "collection" has been replaced w/ pkg resolution conventions & in the latest version of the beta, the cli usage docs include a note about ls only listing opspec 0.1.3 pkgs. Closing this as resolved considering those developments. 

```shell
$ opctl

Usage: opctl [OPTIONS] COMMAND [arg...]

Open source cross platform opspec node

Options:
  -v, --version            Show the version and exit
  --nc, --no-color=false   Disable output coloring

Commands:
  events        Stream events
  ls            List packages (only v0.1.3 opspec packages will be listed)
  node          Manage nodes
  op            Manage ops
  pkg           Manage packages
  run           Start and wait on an op
  self-update   Update opctl

Run 'opctl COMMAND --help' for more information on a command.
```
